Repository festim-dev/FESTIM, pull requests merged in 2023-10, with the labels that each got.

#584 HydrogenTransportProblem class, Mesh and 1Dmesh class
  festim/__init__.py
  festim/hydrogen_transport_problem.py
  festim/mesh/__init__.py
  festim/mesh/mesh.py
  festim/mesh/mesh_1d.py
Labels: enhancement

#589 GitHub actions CI workflow
  .github/workflows/ci.yml
  test/test_example.py
Labels: enhancement

#593 Subdomain classes
  festim/__init__.py
  festim/hydrogen_transport_problem.py
  festim/mesh/mesh.py
  festim/mesh/mesh_1d.py
  festim/subdomain/__init__.py
  festim/subdomain/surface_subdomain.py
  festim/subdomain/volume_subdomain.py
  test/test_permeation_problem.py
  test/test_subdomains.py
Labels: enhancement

#596 Materials class and temperature processing
  festim/__init__.py
  festim/helpers.py
  festim/hydrogen_transport_problem.py
  festim/material.py
  festim/mesh/mesh.py
  festim/mesh/mesh_1d.py
  festim/species.py
  festim/subdomain/volume_subdomain.py
  test/test_helpers.py
  test/test_material.py
  test/test_permeation_problem.py
  test/test_temperature.py
Labels: enhancement, fenicsx

#599 Mesh properties fdim and vdim
  festim/hydrogen_transport_problem.py
  festim/mesh/mesh.py
  festim/mesh/mesh_1d.py
  test/test_mesh.py
Labels: fenicsx

#608 Remove conda workflow temporarily
  .github/workflows/ci.yml
Labels: fenicsx

#605 Mesh normal as property of F.Mesh
  festim/hydrogen_transport_problem.py
  festim/mesh/mesh.py
  test/test_permeation_problem.py
Labels: enhancement, fenicsx

#607 benchmarking script
  .github/workflows/benchmark.yml
  festim/hydrogen_transport_problem.py
  test/benchmark.py
  test/test_permeation_problem.py
Labels: fenicsx

#609 Dirichlet BC attempt 3
  festim/__init__.py
  festim/boundary_conditions/dirichlet_bc.py
  festim/boundary_conditions/sieverts_bc.py
  festim/hydrogen_transport_problem.py
  test/test_dirichlet_bc.py
  test/test_permeation_problem.py
  test/test_sievertsbc.py
Labels: fenicsx

#615 Fix ufl cell vs basix cell
  festim/hydrogen_transport_problem.py
  test/benchmark.py
  test/test_permeation_problem.py
Labels: fenicsx

#614 Reactions
  festim/__init__.py
  festim/reaction.py
  festim/species.py
  test/test_reaction.py
  test/test_species.py
Labels: fenicsx

#617 Multispecies support
  festim/__init__.py
  festim/boundary_conditions/dirichlet_bc.py
  festim/exports/vtx.py
  festim/exports/xdmf.py
  festim/hydrogen_transport_problem.py
  festim/material.py
  festim/species.py
  festim/subdomain/surface_subdomain.py
  test/benchmark.py
  test/test_dirichlet_bc.py
  test/test_material.py
  test/test_multispecies_problem.py
  test/test_permeation_problem.py
  test/test_subdomains.py
  test/test_vtx.py
  test/test_xdmf.py
Labels: enhancement, fenicsx

#621 Iterate method
  festim/hydrogen_transport_problem.py
  test/test_h_transport_problem.py
Labels: fenicsx
