Repository festim-dev/FESTIM, pull requests merged in 2023-12, with the labels that each got.

#641 Mesh from XDMF files
  examples/tds_example.py
  festim/__init__.py
  festim/hydrogen_transport_problem.py
  festim/mesh/mesh_1d.py
  festim/mesh/mesh_from_xdmf.py
  festim/subdomain/surface_subdomain.py
  festim/subdomain/surface_subdomain_1d.py
  festim/subdomain/volume_subdomain.py
  festim/subdomain/volume_subdomain_1d.py
  test/test_dirichlet_bc.py
  test/test_h_transport_problem.py
  test/test_mesh.py
  test/test_subdomains.py
Labels: enhancement, fenicsx

#654 Adaptive stepsize
  festim/hydrogen_transport_problem.py
  festim/stepsize.py
  test/test_h_transport_problem.py
  test/test_stepsize.py
Labels: fenicsx

#657 Trap convenience class
  festim/hydrogen_transport_problem.py
  festim/species.py
  test/test_h_transport_problem.py
  test/test_species.py
Labels: enhancement, fenicsx

#640 Initial Conditions
  festim/__init__.py
  festim/hydrogen_transport_problem.py
  festim/initial_condition.py
  test/test_h_transport_problem.py
  test/test_initial_condition.py
Labels: fenicsx

#664 Update theory.rst
  docs/environment.yml
  docs/source/bibliography/references.bib
  docs/source/conf.py
  docs/source/images/recomb_sketch.png
  docs/source/theory.rst
Labels: Documentation

#670 Fix TOC in Theory
  docs/environment.yml
Labels: bug, Documentation

#669 Update metadata of documentation
  docs/source/conf.py
Labels: Documentation

#674 Fix bug is_steady_state with TemperatureFromXDMF
  festim/temperature/temperature_from_xdmf.py
  test/unit/test_temperature.py
Labels: bug
