Repository festim-dev/FESTIM, pull requests merged in 2024-08, with the labels that each got.

#835 Correct units for cylindrical and spherical fluxes
  festim/exports/derived_quantities/surface_flux.py
  test/unit/test_exports/test_derived_quantities/test_derived_quantities.py
  test/unit/test_exports/test_derived_quantities/test_surface_flux.py
Labels: bug

#858 Documentation: typo value not in code #843
  docs/source/userguide/boundary_conditions.rst
Labels: Documentation

#853 Add University of Tsukuba on the user map
  docs/source/map.json
Labels: Documentation

#865 Details for contribution workflow
  docs/source/devguide/index.rst
Labels: Documentation

#862 Store user logos locally to avoid missing markers in map
  docs/source/images/user_logos/Beihang_University.png
  docs/source/images/user_logos/Commonwealth_Fusion_Systems Devens_MA_USA.png
  docs/source/images/user_logos/Cranfield_University_UK.png
  docs/source/images/user_logos/ENEA.png
  docs/source/images/user_logos/ENI.png
  docs/source/images/user_logos/Frazer_Nash.png
  docs/source/images/user_logos/IRFM_cadarache_France.png
  docs/source/images/user_logos/ITER_organization_France.png
  docs/source/images/user_logos/Institut_Jožef_Stefan.png
  docs/source/images/user_logos/Institute_of_plasma_physics_Chinese_academy_of_sciences.png
  docs/source/images/user_logos/Kyoto_Fusioneering.png
  docs/source/images/user_logos/LSPM_Villetaneuse_France.png
  docs/source/images/user_logos/Logo_of_University_of_Tsukuba.png
  docs/source/images/user_logos/MEPhI_moscow_Russia.png
  docs/source/images/user_logos/MIT_Cambridge_MA_USA.png
  docs/source/images/user_logos/Marathon_Fusion_USA.png
  docs/source/images/user_logos/Oak_Ridge_National_Laboratory.png
  docs/source/images/user_logos/Politecnico_di_Torino.png
  docs/source/images/user_logos/Thea_Energy_USA.png
  docs/source/images/user_logos/UKAEA_UK.png
  docs/source/images/user_logos/University_San_Diego.png
  docs/source/images/user_logos/University_Wisconsin_Madison_USA.png
  docs/source/images/user_logos/University_of_Surrey.png
  docs/source/images/user_logos/University_of_Tsukuba.png
  docs/source/images/user_logos/Zap_Energy.png
  docs/source/images/user_logos/digiLab_UK.png
  docs/source/map.json
  docs/source/map.py
Labels: Documentation

#857 created shared Problem class for HeatTransferProblem and HTransportProblem
  festim/__init__.py
  festim/heat_transfer_problem.py
  festim/hydrogen_transport_problem.py
  festim/problem.py
Labels: enhancement, fenicsx

#874 Wrong value for error_on_nonconvergence in `NewtonSolver`
  festim/concentration/traps/extrinsic_trap.py
  festim/temperature/temperature_solver.py
  test/unit/test_temperature.py
  test/unit/test_traps/test_extrinsic_trap.py
Labels: bug

#872 added WSL and Anaconda instructions
  docs/source/installation.rst
Labels: Documentation

#877 moving setup.cfg and setup.py to pyproject.toml
  festim/boundary_conditions/fluxes/surface_kinetics.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: Distribution

#764 Update dolfinx 0.8
  .github/workflows/ci_conda.yml
  .github/workflows/ci_docker.yml
  festim/boundary_conditions/dirichlet_bc.py
  test/system_tests/test_1_mobile_1_trap.py
  test/system_tests/test_1_mobile_species.py
  test/system_tests/test_fluxes.py
  test/system_tests/test_heat_transfer.py
  test/system_tests/tools.py
  test/test_dirichlet_bc.py
  test/test_h_transport_problem.py
  test/test_heat_transfer_problem.py
  test/test_initial_condition.py
  test/test_mesh.py
  test/test_surface_quantity.py
  test/test_total_volume.py
Labels: fenicsx

#879 added possibility to not display the progress bar
  festim/problem.py
  test/test_h_transport_problem.py
  test/test_heat_transfer_problem.py
Labels: enhancement, fenicsx
