Repository festim-dev/FESTIM, pull requests merged in 2024-04, with the labels that each got.

#737 fenicsx: Flux BC support
  festim/__init__.py
  festim/boundary_conditions/flux_bc.py
  festim/heat_transfer_problem.py
  festim/hydrogen_transport_problem.py
  festim/source.py
  test/system_tests/test_fluxes.py
  test/system_tests/test_heat_transfer.py
  test/test_flux_bc.py
  test/test_h_transport_problem.py
  test/test_heat_transfer_problem.py
Labels: enhancement, fenicsx

#747 Surface Flux fix
  festim/exports/surface_flux.py
  festim/hydrogen_transport_problem.py
  test/test_surface_quantity.py
Labels: fenicsx

#763 Adds NumFOCUS sponsorship
  README.md
Labels: Documentation

#761 Map of institutions in documentation
  docs/environment.yml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/map.json
  docs/source/map.py
Labels: Documentation

#759 `tqdm.auto` instead of `tqdm.autonotebook` + refresh
  festim/hydrogen_transport_problem.py
Labels: enhancement, fenicsx

#750 Refactor `create_value_fenics` for source and fluxes
  festim/boundary_conditions/flux_bc.py
  festim/heat_transfer_problem.py
  festim/hydrogen_transport_problem.py
  festim/source.py
  test/test_flux_bc.py
  test/test_h_transport_problem.py
  test/test_heat_transfer_problem.py
  test/test_source.py
Labels: fenicsx
