Repository festim-dev/FESTIM, pull requests merged in 2024-01, with the labels that each got.

#682 Fix bug with calculations on small timescales
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/txt_export.py
  festim/generic_simulation.py
  festim/stepsize.py
  test/system/test_misc.py
Labels: bug

#679 Radioactive decay
  docs/source/api/sources.rst
  festim/__init__.py
  festim/concentration/mobile.py
  festim/concentration/traps/trap.py
  festim/generic_simulation.py
  festim/sources/radioactive_decay.py
  test/system/test_system.py
  test/unit/test_mobile.py
  test/unit/test_radioactive_decay.py
Labels: enhancement

#681 Improve docs
  CITATION.cff
  docs/source/api/settings.rst
  docs/source/conf.py
  docs/source/devguide/index.rst
  docs/source/userguide/beginners_guide.rst
  docs/source/userguide/boundary_conditions.rst
  docs/source/userguide/export_post_processing.rst
  docs/source/userguide/index.rst
  docs/source/userguide/initial_conditions.rst
  docs/source/userguide/materials.rst
  docs/source/userguide/mesh.rst
  docs/source/userguide/settings.rst
  docs/source/userguide/simulations.rst
  docs/source/userguide/sources.rst
  docs/source/userguide/stepsize.rst
  docs/source/userguide/temperature.rst
  docs/source/userguide/traps.rst
  docs/source/userguide/troubleshooting.rst
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/xdmf_export.py
  setup.cfg
Labels: Documentation

#687 Documentation: getting started to installation
  docs/source/index.rst
  docs/source/installation.rst
Labels: Documentation

#690 Soret coefficient as a function of temperature
  docs/source/theory.rst
  docs/source/userguide/materials.rst
  festim/concentration/mobile.py
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/derived_quantities/derived_quantity.py
  festim/exports/derived_quantities/surface_flux.py
  festim/materials/material.py
  festim/materials/materials.py
  test/system/test_system.py
  test/unit/test_exports/test_derived_quantities/test_derived_quantities.py
  test/unit/test_exports/test_derived_quantities/test_surface_flux.py
  test/unit/test_materials.py
Labels: enhancement

#692 RaiseError when DirichletBC is set with another BC
  festim/generic_simulation.py
  test/system/test_misc.py
Labels: enhancement
