Repository festim-dev/FESTIM, pull requests merged in 2024-07, with the labels that each got.

#735 DerivedQuantities for fenicsx
  festim/__init__.py
  festim/exports/average_surface.py
  festim/exports/average_volume.py
  festim/exports/maximum_surface.py
  festim/exports/maximum_volume.py
  festim/exports/minimum_surface.py
  festim/exports/minimum_volume.py
  festim/exports/surface_flux.py
  festim/exports/surface_quantity.py
  festim/exports/total_surface.py
  festim/exports/total_volume.py
  festim/exports/volume_quantity.py
  festim/hydrogen_transport_problem.py
  festim/subdomain/surface_subdomain_1d.py
  festim/subdomain/volume_subdomain_1d.py
  test/test_average_surface.py
  test/test_average_volume.py
  test/test_derived_quantities.py
  test/test_h_transport_problem.py
  test/test_maximum_surface.py
  test/test_maximum_volume.py
  test/test_minimum_surface.py
  test/test_minimum_volume.py
  test/test_surface_quantity.py
  test/test_total_surface.py
  test/test_total_volume.py
Labels: fenicsx

#794 Move icons to header in docs
  docs/source/conf.py
Labels: Documentation

#795 Fix attributes typo in docs
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/derived_quantities/hydrogen_flux.py
  festim/exports/derived_quantities/surface_flux.py
  festim/exports/derived_quantities/thermal_flux.py
  festim/exports/derived_quantities/total_surface.py
  festim/exports/derived_quantities/total_volume.py
Labels: Documentation

#796 Fix bug with XDMF export in mode last
  festim/exports/xdmf_export.py
  test/system/test_misc.py
Labels: bug

#791 `SurfaceKinetics` BC
  docs/source/api/boundary_conditions.rst
  docs/source/api/exports.rst
  festim/__init__.py
  festim/boundary_conditions/fluxes/surface_kinetics.py
  festim/concentration/mobile.py
  festim/exports/derived_quantities/adsorbed_hydrogen.py
  festim/exports/exports.py
  festim/generic_simulation.py
  festim/h_transport_problem.py
  test/simulation/test_postprocessing_integration.py
  test/system/test_misc.py
  test/unit/test_boundary_conditions.py
  test/unit/test_exports/test_derived_quantities/test_adsorbed_hydrogen.py
  test/unit/test_exports/test_derived_quantities/test_derived_quantities.py
  test/unit/test_exports/test_derived_quantities/tools.py
Labels: enhancement

#797 Docs fixes
  docs/source/api/boundary_conditions.rst
  docs/source/api/materials.rst
  docs/source/api/sources.rst
  docs/source/conf.py
  docs/source/devguide/index.rst
  docs/source/theory.rst
  docs/source/userguide/beginners_guide.rst
  docs/source/userguide/boundary_conditions.rst
  docs/source/userguide/index.rst
  docs/source/userguide/materials.rst
  docs/source/userguide/sources.rst
  docs/source/userguide/troubleshooting.rst
  festim/boundary_conditions/dirichlets/sieverts_bc.py
  festim/concentration/traps/extrinsic_trap.py
  festim/concentration/traps/trap.py
  festim/exports/derived_quantities/average_surface.py
  festim/exports/derived_quantities/average_volume.py
  festim/exports/derived_quantities/hydrogen_flux.py
  festim/exports/derived_quantities/maximum_surface.py
  festim/exports/derived_quantities/maximum_volume.py
  festim/exports/derived_quantities/minimum_surface.py
  festim/exports/derived_quantities/minimum_volume.py
  festim/exports/derived_quantities/point_value.py
  festim/exports/derived_quantities/surface_flux.py
  festim/exports/derived_quantities/thermal_flux.py
  festim/exports/derived_quantities/total_surface.py
  festim/exports/derived_quantities/total_volume.py
Labels: Documentation

#780 Test documentation code blocks
  .github/workflows/doctest.yml
  docs/environment.yml
  docs/source/userguide/boundary_conditions.rst
  docs/source/userguide/export_post_processing.rst
  docs/source/userguide/initial_conditions.rst
  docs/source/userguide/materials.rst
  docs/source/userguide/mesh.rst
  docs/source/userguide/newton_solver.rst
  docs/source/userguide/settings.rst
  docs/source/userguide/sources.rst
  docs/source/userguide/stepsize.rst
  docs/source/userguide/temperature.rst
  docs/source/userguide/traps.rst
  docs/source/userguide/troubleshooting.rst
Labels: Documentation

#801 Update the information in the XDMF section
  docs/source/images/paraview_guide_1.png
  docs/source/images/paraview_guide_2.png
  docs/source/userguide/export_post_processing.rst
Labels: Documentation

#805 `SurfaceKinetics` docs and form
  festim/boundary_conditions/fluxes/surface_kinetics.py
  test/system/test_system.py
  test/unit/test_boundary_conditions.py
Labels: bug

#809 Add ornl
  docs/source/map.json
Labels: Documentation

#815 List of maintainers in docs
  docs/source/devguide/index.rst
Labels: Documentation

#817 Filter method docs
  docs/source/userguide/export_post_processing.rst
Labels: Documentation

#812 Error if temperature BC or source with `F.Temperature`
  festim/generic_simulation.py
  test/system/test_misc.py
  test/unit/test_boundary_conditions.py
Labels: enhancement

#808 Theory and UG for the `SurfaceKinetics` BC
  docs/source/bibliography/references.bib
  docs/source/images/potential_diagram.png
  docs/source/theory.rst
  docs/source/userguide/boundary_conditions.rst
  docs/source/userguide/export_post_processing.rst
Labels: Documentation

#827 No python version in CI
  .github/workflows/ci.yml
Labels: bug

#823 Soret effect for cylindrical and spherical systems
  festim/concentration/mobile.py
  festim/exports/derived_quantities/surface_flux.py
  test/system/test_cylindrical_coordinates.py
  test/system/test_spherical_coordinates.py
  test/unit/test_exports/test_derived_quantities/test_surface_flux.py
  test/unit/test_mobile.py
Labels: enhancement

#831 Fix SurfaceFlux with Soret
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/derived_quantities/surface_flux.py
  festim/generic_simulation.py
  test/system/test_misc.py
  test/unit/test_exports/test_derived_quantities/test_surface_flux.py
Labels: bug

#832 allowed_meshes property for derived quantities
  festim/exports/derived_quantities/average_surface.py
  festim/exports/derived_quantities/average_volume.py
  festim/exports/derived_quantities/derived_quantity.py
  festim/exports/derived_quantities/surface_flux.py
  festim/exports/derived_quantities/total_surface.py
  festim/exports/derived_quantities/total_volume.py
  festim/generic_simulation.py
  test/system/test_cylindrical_coordinates.py
  test/system/test_spherical_coordinates.py
Labels: bug, enhancement

#836 Fixed Simulation.exports setter
  festim/generic_simulation.py
  test/simulation/test_construction.py
  test/simulation/test_postprocessing_integration.py
Labels: bug
