Repository festim-dev/FESTIM, pull requests merged in 2024-11, with the labels that each got.

#909 Fix solver options
  src/festim/hydrogen_transport_problem.py
  src/festim/problem.py
  test/system_tests/test_misc.py
Labels: bug, fenicsx

#753 Surface reactions
  examples/surface_reaction_example.py
  src/festim/__init__.py
  src/festim/boundary_conditions/__init__.py
  src/festim/boundary_conditions/surface_reaction.py
  src/festim/hydrogen_transport_problem.py
  test/system_tests/test_surface_reactions.py
  test/test_h_transport_problem.py
Labels: enhancement, fenicsx

#894 Various fixes
  docs/source/devguide/index.rst
  docs/source/userguide/beginners_guide.rst
  src/festim/hydrogen_transport_problem.py
  src/festim/problem.py
Labels: Documentation, fenicsx

#733 Reset derived quantity objects data and t at the beginning of a simulation
  src/festim/hydrogen_transport_problem.py
  test/test_h_transport_problem.py
Labels: bug, fenicsx

#885 GMSH workflow
  docs/source/images/gmsh_tut_1.png
  docs/source/images/gmsh_tut_2.png
  docs/source/images/gmsh_tut_3.png
  docs/source/images/gmsh_tut_4.png
  docs/source/images/gmsh_tut_5.png
  docs/source/userguide/mesh.rst
Labels: Documentation

#916 Adaptive timestepping
  src/festim/stepsize.py
  test/test_stepsize.py
Labels: enhancement, fenicsx

#917 fenicsx installation instructions
  docs/source/installation.rst
Labels: Documentation, fenicsx

#918 Penalty method for interfaces
  src/festim/__init__.py
  src/festim/hydrogen_transport_problem.py
  src/festim/material.py
  test/system_tests/test_multi_mat_penalty.py
Labels: enhancement, fenicsx

#924 added styling
  docs/source/_static/style.css
Labels: Documentation
