Repository festim-dev/FESTIM, pull requests merged in 2024-06, with the labels that each got.

#762 Additional buttons in header
  docs/source/conf.py
Labels: Documentation

#771 Update docstrings for `Temperature`
  festim/temperature/temperature.py
Labels: Documentation

#774 IC improvements for Heat Transfer
  docs/source/userguide/temperature.rst
  festim/temperature/temperature_solver.py
  test/system/test_misc.py
  test/unit/test_temperature.py
Labels: enhancement

#770 Temperature can be given as float or sp.Expr
  docs/source/userguide/temperature.rst
  festim/generic_simulation.py
  test/simulation/test_initialise.py
Labels: enhancement

#734 Custom solver
  festim/__init__.py
  festim/concentration/traps/extrinsic_trap.py
  festim/concentration/traps/traps.py
  festim/h_transport_problem.py
  festim/nonlinear_problem.py
  festim/settings.py
  festim/temperature/temperature_solver.py
  test/h_transport_problem/test_solving.py
  test/heat_transfer_problem/test_solving.py
  test/system/test_misc.py
  test/unit/test_traps/test_extrinsic_trap.py
  test/unit/test_traps/test_neutron_induced_trap.py
Labels: enhancement

#777 Documentation: stepsize and Newton Solver
  docs/source/userguide/index.rst
  docs/source/userguide/newton_solver.rst
  docs/source/userguide/settings.rst
  docs/source/userguide/stepsize.rst
Labels: Documentation

#779 Documentation guide
  docs/environment.yml
  docs/source/devguide/index.rst
Labels: Documentation

#776 SALOME meshing guide
  docs/environment.yml
  docs/source/conf.py
  docs/source/files/Mesh_1.med
  docs/source/images/salome_guide_1.png
  docs/source/images/salome_guide_10.png
  docs/source/images/salome_guide_11.png
  docs/source/images/salome_guide_12.png
  docs/source/images/salome_guide_13.png
  docs/source/images/salome_guide_14.png
  docs/source/images/salome_guide_2.png
  docs/source/images/salome_guide_3.png
  docs/source/images/salome_guide_4.png
  docs/source/images/salome_guide_5.png
  docs/source/images/salome_guide_6.png
  docs/source/images/salome_guide_7.png
  docs/source/images/salome_guide_8.png
  docs/source/images/salome_guide_9.png
  docs/source/images/salome_guide_cad_1.png
  docs/source/images/salome_guide_cad_2.png
  docs/source/images/salome_guide_cad_3.png
  docs/source/userguide/mesh.rst
Labels: Documentation

#784 Pin version in benchmark
  .github/workflows/benchmark.yml
Labels: fenicsx

#786 Fix user map + new institutions
  docs/source/map.json
  docs/source/map.py
Labels: Documentation
