Repository festim-dev/FESTIM, pull requests merged in 2024-05, with the labels that each got.

#752 Robin boundary conditions for ParticleFlux
  festim/boundary_conditions/flux_bc.py
  test/test_flux_bc.py
Labels: enhancement, fenicsx

#730 Arbitrary reaction
  examples/multi_isotope_trapping_example.py
  examples/tds_example.py
  examples/trapping_example.py
  festim/hydrogen_transport_problem.py
  festim/reaction.py
  festim/species.py
  test/system_tests/test_1_mobile_1_trap.py
  test/system_tests/test_reaction_not_in_every_volume.py
  test/test_complex_reaction.py
  test/test_reaction.py
Labels: enhancement, fenicsx

#767 Fix units for "retention" with TotalVolume and TotalSurface
  festim/exports/derived_quantities/total_surface.py
  festim/exports/derived_quantities/total_volume.py
  test/unit/test_exports/test_exports.py
Labels: bug

#768 Error message when temperature is not defined
  festim/generic_simulation.py
  test/simulation/test_initialise.py
Labels: enhancement

#769 Add error message when no final time is provided in transient simulations
  festim/generic_simulation.py
  test/simulation/test_initialise.py
  test/system/test_misc.py
Labels: enhancement
