Repository festim-dev/FESTIM, pull requests merged in 2024-03, with the labels that each got.

#706 Patch derived quantity overwriting csv file
  festim/exports/surface_quantity.py
  test/test_surface_quantity.py
Labels: bug, fenicsx

#703 Total volume quantity
  festim/__init__.py
  festim/exports/total_volume.py
  festim/exports/volume_quantity.py
  festim/hydrogen_transport_problem.py
  test/test_multispecies_problem.py
  test/test_surface_quantity.py
  test/test_total_volume.py
  test/test_volume_quantity.py
Labels: enhancement, fenicsx

#707 Add `DissociationFlux` to API documentation
  docs/source/api/boundary_conditions.rst
Labels: Documentation

#704 `Reaction.product` now accepts a list of `Species`
  festim/hydrogen_transport_problem.py
  festim/reaction.py
  test/test_complex_reaction.py
  test/test_reaction.py
Labels: enhancement, fenicsx

#689 Cylindrical and spherical versions of SurfaceFlux
  docs/source/api/exports.rst
  festim/__init__.py
  festim/exports/derived_quantities/surface_flux.py
  festim/generic_simulation.py
  test/simulation/test_initialise.py
  test/unit/test_exports/test_derived_quantities/test_surface_flux.py
Labels: enhancement

#717 Update citation and add missing publications
  CITATION.cff
  docs/source/index.rst
  docs/source/publications.rst
Labels: Documentation

#716 Adding copy button to the documentation
  docs/environment.yml
  docs/source/conf.py
Labels: Documentation

#721 MMS testing
  festim/source.py
  test/system_tests/__init__.py
  test/system_tests/test_1_mobile_1_trap.py
  test/system_tests/test_1_mobile_species.py
  test/system_tests/test_reaction_not_in_every_volume.py
  test/system_tests/tools.py
  test/test_source.py
Labels: enhancement, fenicsx

#686 Heat transfer class
  convergence_rates.py
  festim/__init__.py
  festim/boundary_conditions/dirichlet_bc.py
  festim/exports/vtx.py
  festim/heat_transfer_problem.py
  festim/initial_condition.py
  festim/material.py
  festim/source.py
  setup.cfg
  test/test_heat_transfer_problem.py
  test/test_initial_condition.py
  test/test_source.py
Labels: enhancement, fenicsx

#725 Hotfix 1.2.1
  festim/concentration/traps/traps.py
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/exports.py
  festim/materials/materials.py
  test/unit/test_exports/test_derived_quantities/test_derived_quantities.py
  test/unit/test_exports/test_exports.py
  test/unit/test_materials.py
  test/unit/test_traps/test_traps.py
Labels: bug
