Repository festim-dev/FESTIM, pull requests merged in 2024-02, with the labels that each got.

#694 F.Materials -> subclass of list
  festim/concentration/mobile.py
  festim/concentration/theta.py
  festim/concentration/traps/trap.py
  festim/generic_simulation.py
  festim/materials/materials.py
  festim/meshing/mesh_1d.py
  festim/temperature/temperature_solver.py
  test/system/test_misc.py
  test/unit/test_materials.py
Labels: enhancement

#696 Updating getting_started link in README.md
  README.md
Labels: Documentation

#697 `F.Traps` and `F.DerivedQuantities` -> subclasses of list
  festim/concentration/mobile.py
  festim/concentration/traps/traps.py
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/exports.py
  festim/generic_simulation.py
  festim/h_transport_problem.py
  festim/materials/materials.py
  test/h_transport_problem/test_initialisation.py
  test/h_transport_problem/test_solving.py
  test/simulation/test_postprocessing_integration.py
  test/system/test_system.py
  test/unit/test_exports/test_derived_quantities/test_derived_quantities.py
  test/unit/test_exports/test_exports.py
  test/unit/test_materials.py
  test/unit/test_mobile.py
  test/unit/test_traps/test_traps.py
Labels: enhancement

#698 `max_stepsize` attribute for `festim.Stepsize`
  docs/source/userguide/stepsize.rst
  festim/stepsize.py
  test/unit/test_stepsize.py
Labels: enhancement

#699 Small update of Docs
  docs/source/api/temperature.rst
  docs/source/theory.rst
  docs/source/userguide/boundary_conditions.rst
  festim/boundary_conditions/dirichlets/dc_imp.py
Labels: Documentation

#677 Custom fenics mesh
  festim/hydrogen_transport_problem.py
  festim/mesh/mesh.py
  test/test_h_transport_problem.py
  test/test_mesh.py
Labels: enhancement, fenicsx

#683 Reduce number of warnings
  .github/workflows/ci_conda.yml
  .github/workflows/ci_docker.yml
  festim/boundary_conditions/dirichlet_bc.py
  festim/hydrogen_transport_problem.py
  festim/initial_condition.py
  festim/mesh/mesh_1d.py
  festim/source.py
  test/benchmark.py
  test/test_h_transport_problem.py
  test/test_initial_condition.py
  test/test_reaction.py
  test/test_source.py
  test/test_species.py
  test/test_surface_quantity.py
  test/test_vtx.py
  test/test_xdmf.py
Labels: bug, fenicsx
