Repository festim-dev/FESTIM, pull requests merged in 2025-04, with the labels that each got.

#963 Refactoring
  examples/advection_diffusion_multi_material.py
  examples/multi_material_1d.py
  examples/multi_material_2d.py
  examples/multi_material_2d_bis.py
  examples/multi_material_transient.py
  examples/multi_material_with_one_material.py
  src/festim/__init__.py
  src/festim/coupled_heat_hydrogen_problem.py
  src/festim/hydrogen_transport_problem.py
  src/festim/problem_change_of_var.py
  src/festim/reaction.py
  src/festim/species.py
  src/festim/subdomain/volume_subdomain.py
  test/system_tests/test_advection_term_integration.py
  test/system_tests/test_multi_mat_penalty.py
  test/system_tests/test_multi_material.py
  test/system_tests/test_multi_material_change_of_var.py
  test/test_coupled_heat_hydrogen_problem.py
  test/test_vtx.py
Labels: fenicsx

#977 Remove velocity field export from test
  test/system_tests/test_advection_term_integration.py
Labels: fenicsx

#976 API documentation for fenicsx branch
  .gitignore
  docs/source/api/index.rst
  src/festim/__init__.py
  src/festim/boundary_conditions/__init__.py
  src/festim/boundary_conditions/dirichlet_bc.py
  src/festim/boundary_conditions/flux_bc.py
  src/festim/boundary_conditions/henrys_bc.py
  src/festim/boundary_conditions/sieverts_bc.py
  src/festim/coupled_heat_hydrogen_problem.py
  src/festim/exports/__init__.py
  src/festim/exports/average_surface.py
  src/festim/exports/average_volume.py
  src/festim/exports/maximum_surface.py
  src/festim/exports/maximum_volume.py
  src/festim/exports/minimum_surface.py
  src/festim/exports/minimum_volume.py
  src/festim/exports/surface_flux.py
  src/festim/exports/surface_quantity.py
  src/festim/exports/total_surface.py
  src/festim/exports/total_volume.py
  src/festim/exports/vtx.py
  src/festim/exports/xdmf.py
  src/festim/initial_condition.py
  src/festim/material.py
  src/festim/mesh/__init__.py
  src/festim/mesh/mesh_1d.py
  src/festim/mesh/mesh_from_xdmf.py
  src/festim/reaction.py
  src/festim/species.py
  src/festim/subdomain/__init__.py
  src/festim/subdomain/interface.py
  src/festim/subdomain/surface_subdomain_1d.py
  src/festim/subdomain/volume_subdomain_1d.py
  src/festim/trap.py
Labels: Documentation, fenicsx

#984 nmm_interpolation function options
  src/festim/helpers.py
Labels: enhancement, fenicsx

#981 Fix locate entities
  src/festim/exports/maximum_surface.py
  src/festim/exports/maximum_volume.py
  src/festim/exports/minimum_surface.py
  src/festim/exports/minimum_volume.py
  src/festim/hydrogen_transport_problem.py
  src/festim/mesh/mesh.py
  src/festim/subdomain/surface_subdomain.py
  src/festim/subdomain/volume_subdomain.py
  test/system_tests/test_misc.py
  test/test_h_transport_problem.py
  test/test_maximum_surface.py
  test/test_maximum_volume.py
  test/test_minimum_surface.py
  test/test_minimum_volume.py
  test/test_subdomains.py
Labels: bug, fenicsx
