Repository festim-dev/FESTIM, pull requests merged in 2025-07, with the labels that each got.

#1010 Fix for `MaximumSurface` and `MinimumSurface`
  festim/exports/derived_quantities/derived_quantities.py
  festim/exports/derived_quantities/maximum_surface.py
  festim/exports/derived_quantities/minimum_surface.py
  test/system/test_misc.py
  test/unit/test_exports/test_derived_quantities/test_maximum_surface.py
  test/unit/test_exports/test_derived_quantities/test_minimum_surface.py
Labels: bug

#1006 New SNES newton solver for dolfinx 0.10
  src/festim/problem.py
  test/benchmark.py
  test/system_tests/test_io.py
  test/test_coupled_heat_hydrogen_problem.py
  test/test_h_transport_problem.py
  test/test_multispecies_problem.py
  test/test_permeation_problem.py
  test/test_settings.py
Labels: enhancement, fenicsx

#1005 Simplify `SurfaceSubdomain`
  src/festim/__init__.py
  src/festim/mesh/mesh.py
  src/festim/subdomain/__init__.py
  src/festim/subdomain/surface_subdomain.py
  src/festim/subdomain/surface_subdomain_1d.py
  test/test_subdomains.py
Labels: enhancement, fenicsx

#1015 Profile 1d 1 species
  src/festim/hydrogen_transport_problem.py
  test/test_profile.py
Labels: bug, fenicsx

#1017 Add `times` argument to ProfileExport
  src/festim/exports/profile_1d.py
  src/festim/exports/vtx.py
  src/festim/heat_transfer_problem.py
  src/festim/helpers.py
  src/festim/hydrogen_transport_problem.py
  test/test_helpers.py
  test/test_profile.py
  test/test_vtx.py
Labels: enhancement, fenicsx

#1011 Cylindrical and Spherical coordinate support
  src/festim/exports/surface_flux.py
  src/festim/exports/surface_quantity.py
  src/festim/exports/volume_quantity.py
  src/festim/hydrogen_transport_problem.py
  src/festim/mesh/mesh.py
  test/benchmark.py
  test/system_tests/test_cylindrical_coordinates.py
  test/system_tests/test_spherical_coordinates.py
  test/test_h_transport_problem.py
  test/test_mesh.py
Labels: enhancement, fenicsx
